[project]
name = "pyclaudecli"
version = "0.1.0"
description = "python cli claude clone app which uses aws bedrock foundational model"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "rich>=14.2.0",
    "typer>=0.21.0",
    "pyperclip>=1.8.2",
    "prompt_toolkit>=3.0.0",
    "strands-agents>=1.21.0",
    "strands-agents-tools>=0.2.19",
]
